tournament:
    resource: "@TournamentBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

