services:
    kernel.listener.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    app.service.product:
        class: AppBundle\Services\ProductService
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@jms_serializer'
