<?php

namespace TournamentBundle\Repository;

/**
 * RuleFFAGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleFFAGameRepository extends \Doctrine\ORM\EntityRepository
{
}
