<?php

namespace TournamentBundle\Repository;

/**
 * RuleFFARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleFFARepository extends \Doctrine\ORM\EntityRepository
{
}
