<?php

namespace TournamentBundle\Repository;

/**
 * ScoreFFAGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreFFAGameRepository extends \Doctrine\ORM\EntityRepository
{
}
