<?php

namespace TournamentBundle\Repository;

/**
 * ScoreFFARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreFFARepository extends \Doctrine\ORM\EntityRepository
{
}
